# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.relationusage_api import RelationusageApi


class TestRelationusageApi(unittest.TestCase):
    """ RelationusageApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.relationusage_api.RelationusageApi()

    def tearDown(self):
        pass

    def test_get_relation_usage_between_resource(self):
        """
        Test case for get_relation_usage_between_resource

        All relations used plus count of associations
        """
        pass

    def test_get_relation_usage_pivot_label_resource(self):
        """
        Test case for get_relation_usage_pivot_label_resource

        Relation usage count for all subj x obj category combinations, showing label
        """
        pass

    def test_get_relation_usage_pivot_resource(self):
        """
        Test case for get_relation_usage_pivot_resource

        Relation usage count for all subj x obj category combinations
        """
        pass

    def test_get_relation_usage_resource(self):
        """
        Test case for get_relation_usage_resource

        All relations used plus count of associations
        """
        pass


if __name__ == '__main__':
    unittest.main()
