# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """ SearchApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.search_api.SearchApi()

    def tearDown(self):
        pass

    def test_get_autocomplete(self):
        """
        Test case for get_autocomplete

        Returns list of matching concepts or entities using lexical search
        """
        pass

    def test_get_search_entities(self):
        """
        Test case for get_search_entities

        Returns list of matching concepts or entities using lexical search
        """
        pass


if __name__ == '__main__':
    unittest.main()
