# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.owlontology_api import OwlontologyApi


class TestOwlontologyApi(unittest.TestCase):
    """ OwlontologyApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.owlontology_api.OwlontologyApi()

    def tearDown(self):
        pass

    def test_get_dl_query(self):
        """
        Test case for get_dl_query

        Placeholder - use OWLery for now
        """
        pass

    def test_get_dl_query_0(self):
        """
        Test case for get_dl_query_0

        Placeholder - use direct SPARQL endpoint for now
        """
        pass


if __name__ == '__main__':
    unittest.main()
