# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.identifiermapper_api import IdentifiermapperApi


class TestIdentifiermapperApi(unittest.TestCase):
    """ IdentifiermapperApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.identifiermapper_api.IdentifiermapperApi()

    def tearDown(self):
        pass

    def test_get_prefix_collection(self):
        """
        Test case for get_prefix_collection

        TODO maps a list of identifiers from a source to a target
        """
        pass


if __name__ == '__main__':
    unittest.main()
