# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.variationset_api import VariationsetApi


class TestVariationsetApi(unittest.TestCase):
    """ VariationsetApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.variationset_api.VariationsetApi()

    def tearDown(self):
        pass

    def test_delete_variant_set_item(self):
        """
        Test case for delete_variant_set_item

        Deletes variant set
        """
        pass

    def test_get_analyze(self):
        """
        Test case for get_analyze

        Returns list of matches
        """
        pass

    def test_get_variant_set_item(self):
        """
        Test case for get_variant_set_item

        Returns a variant set
        """
        pass

    def test_get_variant_sets_archive_collection(self):
        """
        Test case for get_variant_sets_archive_collection

        Returns list of variant sets from a specified time period
        """
        pass

    def test_get_variant_sets_collection(self):
        """
        Test case for get_variant_sets_collection

        Returns list of variant sets
        """
        pass

    def test_post_variant_sets_collection(self):
        """
        Test case for post_variant_sets_collection

        Creates a new variant set
        """
        pass

    def test_put_variant_set_item(self):
        """
        Test case for put_variant_set_item

        Updates a variant set
        """
        pass


if __name__ == '__main__':
    unittest.main()
