# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.bioentityset_api import BioentitysetApi


class TestBioentitysetApi(unittest.TestCase):
    """ BioentitysetApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.bioentityset_api.BioentitysetApi()

    def tearDown(self):
        pass

    def test_get_entity_set_associations(self):
        """
        Test case for get_entity_set_associations

        Returns compact associations for a given input set
        """
        pass

    def test_get_entity_set_graph_resource(self):
        """
        Test case for get_entity_set_graph_resource

        TODO Graph object spanning all entities
        """
        pass

    def test_get_entity_set_over_representation_analysis(self):
        """
        Test case for get_entity_set_over_representation_analysis

        TODO Over-representation analysis
        """
        pass

    def test_get_entity_set_over_representation_analysis_0(self):
        """
        Test case for get_entity_set_over_representation_analysis_0

        TODO Over-representation analysis
        """
        pass

    def test_get_entity_set_summary(self):
        """
        Test case for get_entity_set_summary

        Summary statistics for objects associated
        """
        pass


if __name__ == '__main__':
    unittest.main()
