# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.evidencegraph_api import EvidencegraphApi


class TestEvidencegraphApi(unittest.TestCase):
    """ EvidencegraphApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.evidencegraph_api.EvidencegraphApi()

    def tearDown(self):
        pass

    def test_get_association_object(self):
        """
        Test case for get_association_object

        Returns evidence graph object for a given association
        """
        pass

    def test_get_association_object_0(self):
        """
        Test case for get_association_object_0

        Returns evidence graph as a png
        """
        pass


if __name__ == '__main__':
    unittest.main()
