# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.genotype import Genotype


class TestGenotype(unittest.TestCase):
    """ Genotype unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenotype(self):
        """
        Test Genotype
        """
        model = swagger_client.models.genotype.Genotype()


if __name__ == '__main__':
    unittest.main()
