# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.association_property_value import AssociationPropertyValue


class TestAssociationPropertyValue(unittest.TestCase):
    """ AssociationPropertyValue unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociationPropertyValue(self):
        """
        Test AssociationPropertyValue
        """
        model = swagger_client.models.association_property_value.AssociationPropertyValue()


if __name__ == '__main__':
    unittest.main()
