# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.mart_api import MartApi


class TestMartApi(unittest.TestCase):
    """ MartApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.mart_api.MartApi()

    def tearDown(self):
        pass

    def test_get_mart_case_associations_resource(self):
        """
        Test case for get_mart_case_associations_resource

        Bulk download of case associations
        """
        pass

    def test_get_mart_disease_associations_resource(self):
        """
        Test case for get_mart_disease_associations_resource

        Bulk download of disease associations
        """
        pass

    def test_get_mart_gene_associations_resource(self):
        """
        Test case for get_mart_gene_associations_resource

        Bulk download of gene associations
        """
        pass


if __name__ == '__main__':
    unittest.main()
