# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.identifierprefixes_api import IdentifierprefixesApi


class TestIdentifierprefixesApi(unittest.TestCase):
    """ IdentifierprefixesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.identifierprefixes_api.IdentifierprefixesApi()

    def tearDown(self):
        pass

    def test_get_prefix_collection(self):
        """
        Test case for get_prefix_collection

        Returns list of prefixes
        """
        pass

    def test_get_prefix_collection_0(self):
        """
        Test case for get_prefix_collection_0

        Returns contracted URI
        """
        pass

    def test_get_prefix_collection_1(self):
        """
        Test case for get_prefix_collection_1

        Returns expanded URI
        """
        pass


if __name__ == '__main__':
    unittest.main()
