# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ontolsubgraph_api import OntolsubgraphApi


class TestOntolsubgraphApi(unittest.TestCase):
    """ OntolsubgraphApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ontolsubgraph_api.OntolsubgraphApi()

    def tearDown(self):
        pass

    def test_get_extract_ontology_subgraph_resource(self):
        """
        Test case for get_extract_ontology_subgraph_resource

        Extract a subgraph from an ontology
        """
        pass

    def test_get_test_me(self):
        """
        Test case for get_test_me

        Extract a subgraph from an ontology
        """
        pass


if __name__ == '__main__':
    unittest.main()
