# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Edge(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, sub=None, pred=None, obj=None):
        """
        Edge - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'sub': 'str',
            'pred': 'str',
            'obj': 'str'
        }

        self.attribute_map = {
            'sub': 'sub',
            'pred': 'pred',
            'obj': 'obj'
        }

        self._sub = sub
        self._pred = pred
        self._obj = obj

    @property
    def sub(self):
        """
        Gets the sub of this Edge.
        Subject (source) Node ID

        :return: The sub of this Edge.
        :rtype: str
        """
        return self._sub

    @sub.setter
    def sub(self, sub):
        """
        Sets the sub of this Edge.
        Subject (source) Node ID

        :param sub: The sub of this Edge.
        :type: str
        """

        self._sub = sub

    @property
    def pred(self):
        """
        Gets the pred of this Edge.
        Predicate (relation) ID

        :return: The pred of this Edge.
        :rtype: str
        """
        return self._pred

    @pred.setter
    def pred(self, pred):
        """
        Sets the pred of this Edge.
        Predicate (relation) ID

        :param pred: The pred of this Edge.
        :type: str
        """

        self._pred = pred

    @property
    def obj(self):
        """
        Gets the obj of this Edge.
        Object (target) Node ID

        :return: The obj of this Edge.
        :rtype: str
        """
        return self._obj

    @obj.setter
    def obj(self, obj):
        """
        Sets the obj of this Edge.
        Object (target) Node ID

        :param obj: The obj of this Edge.
        :type: str
        """

        self._obj = obj

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Edge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
