# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EntityReference(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, label=None, id=None, categories=None):
        """
        EntityReference - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'label': 'str',
            'id': 'str',
            'categories': 'list[str]'
        }

        self.attribute_map = {
            'label': 'label',
            'id': 'id',
            'categories': 'categories'
        }

        self._label = label
        self._id = id
        self._categories = categories

    @property
    def label(self):
        """
        Gets the label of this EntityReference.
        RDFS Label

        :return: The label of this EntityReference.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this EntityReference.
        RDFS Label

        :param label: The label of this EntityReference.
        :type: str
        """

        self._label = label

    @property
    def id(self):
        """
        Gets the id of this EntityReference.
        ID or CURIE e.g. MGI:1201606

        :return: The id of this EntityReference.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this EntityReference.
        ID or CURIE e.g. MGI:1201606

        :param id: The id of this EntityReference.
        :type: str
        """

        self._id = id

    @property
    def categories(self):
        """
        Gets the categories of this EntityReference.

        :return: The categories of this EntityReference.
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this EntityReference.

        :param categories: The categories of this EntityReference.
        :type: list[str]
        """

        self._categories = categories

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EntityReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
