# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Gene(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, types=None, categories=None, replaced_by=None, synonyms=None, label=None, deprecated=None, id=None, description=None, consider=None, xrefs=None, taxon=None, transcripts=None, sequence_features=None, function_associations=None, chromosome=None, full_name=None, homology_associations=None, pathway_associations=None, literature_associations=None, interaction_associations=None, disease_associations=None, phenotype_associations=None, summaries=None, genotype_associations=None, families=None, systematic_name=None):
        """
        Gene - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'types': 'list[str]',
            'categories': 'list[str]',
            'replaced_by': 'list[str]',
            'synonyms': 'list[SynonymPropertyValue]',
            'label': 'str',
            'deprecated': 'bool',
            'id': 'str',
            'description': 'str',
            'consider': 'list[str]',
            'xrefs': 'list[str]',
            'taxon': 'Taxon',
            'transcripts': 'list[Transcript]',
            'sequence_features': 'list[SequenceFeature]',
            'function_associations': 'list[Association]',
            'chromosome': 'Chromosome',
            'full_name': 'str',
            'homology_associations': 'list[Association]',
            'pathway_associations': 'list[Association]',
            'literature_associations': 'list[Association]',
            'interaction_associations': 'list[Association]',
            'disease_associations': 'list[Association]',
            'phenotype_associations': 'list[Association]',
            'summaries': 'list[SummaryPropertyValue]',
            'genotype_associations': 'list[Association]',
            'families': 'list[NamedObject]',
            'systematic_name': 'str'
        }

        self.attribute_map = {
            'types': 'types',
            'categories': 'categories',
            'replaced_by': 'replaced_by',
            'synonyms': 'synonyms',
            'label': 'label',
            'deprecated': 'deprecated',
            'id': 'id',
            'description': 'description',
            'consider': 'consider',
            'xrefs': 'xrefs',
            'taxon': 'taxon',
            'transcripts': 'transcripts',
            'sequence_features': 'sequence_features',
            'function_associations': 'function_associations',
            'chromosome': 'chromosome',
            'full_name': 'full_name',
            'homology_associations': 'homology_associations',
            'pathway_associations': 'pathway_associations',
            'literature_associations': 'literature_associations',
            'interaction_associations': 'interaction_associations',
            'disease_associations': 'disease_associations',
            'phenotype_associations': 'phenotype_associations',
            'summaries': 'summaries',
            'genotype_associations': 'genotype_associations',
            'families': 'families',
            'systematic_name': 'systematic_name'
        }

        self._types = types
        self._categories = categories
        self._replaced_by = replaced_by
        self._synonyms = synonyms
        self._label = label
        self._deprecated = deprecated
        self._id = id
        self._description = description
        self._consider = consider
        self._xrefs = xrefs
        self._taxon = taxon
        self._transcripts = transcripts
        self._sequence_features = sequence_features
        self._function_associations = function_associations
        self._chromosome = chromosome
        self._full_name = full_name
        self._homology_associations = homology_associations
        self._pathway_associations = pathway_associations
        self._literature_associations = literature_associations
        self._interaction_associations = interaction_associations
        self._disease_associations = disease_associations
        self._phenotype_associations = phenotype_associations
        self._summaries = summaries
        self._genotype_associations = genotype_associations
        self._families = families
        self._systematic_name = systematic_name

    @property
    def types(self):
        """
        Gets the types of this Gene.

        :return: The types of this Gene.
        :rtype: list[str]
        """
        return self._types

    @types.setter
    def types(self, types):
        """
        Sets the types of this Gene.

        :param types: The types of this Gene.
        :type: list[str]
        """

        self._types = types

    @property
    def categories(self):
        """
        Gets the categories of this Gene.

        :return: The categories of this Gene.
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this Gene.

        :param categories: The categories of this Gene.
        :type: list[str]
        """

        self._categories = categories

    @property
    def replaced_by(self):
        """
        Gets the replaced_by of this Gene.

        :return: The replaced_by of this Gene.
        :rtype: list[str]
        """
        return self._replaced_by

    @replaced_by.setter
    def replaced_by(self, replaced_by):
        """
        Sets the replaced_by of this Gene.

        :param replaced_by: The replaced_by of this Gene.
        :type: list[str]
        """

        self._replaced_by = replaced_by

    @property
    def synonyms(self):
        """
        Gets the synonyms of this Gene.
        list of synonyms or alternate labels

        :return: The synonyms of this Gene.
        :rtype: list[SynonymPropertyValue]
        """
        return self._synonyms

    @synonyms.setter
    def synonyms(self, synonyms):
        """
        Sets the synonyms of this Gene.
        list of synonyms or alternate labels

        :param synonyms: The synonyms of this Gene.
        :type: list[SynonymPropertyValue]
        """

        self._synonyms = synonyms

    @property
    def label(self):
        """
        Gets the label of this Gene.
        RDFS Label

        :return: The label of this Gene.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this Gene.
        RDFS Label

        :param label: The label of this Gene.
        :type: str
        """

        self._label = label

    @property
    def deprecated(self):
        """
        Gets the deprecated of this Gene.
        True if the node is deprecated/obsoleted.

        :return: The deprecated of this Gene.
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """
        Sets the deprecated of this Gene.
        True if the node is deprecated/obsoleted.

        :param deprecated: The deprecated of this Gene.
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def id(self):
        """
        Gets the id of this Gene.
        ID or CURIE e.g. MGI:1201606

        :return: The id of this Gene.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Gene.
        ID or CURIE e.g. MGI:1201606

        :param id: The id of this Gene.
        :type: str
        """

        self._id = id

    @property
    def description(self):
        """
        Gets the description of this Gene.
        full text description

        :return: The description of this Gene.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Gene.
        full text description

        :param description: The description of this Gene.
        :type: str
        """

        self._description = description

    @property
    def consider(self):
        """
        Gets the consider of this Gene.

        :return: The consider of this Gene.
        :rtype: list[str]
        """
        return self._consider

    @consider.setter
    def consider(self, consider):
        """
        Sets the consider of this Gene.

        :param consider: The consider of this Gene.
        :type: list[str]
        """

        self._consider = consider

    @property
    def xrefs(self):
        """
        Gets the xrefs of this Gene.
        Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 

        :return: The xrefs of this Gene.
        :rtype: list[str]
        """
        return self._xrefs

    @xrefs.setter
    def xrefs(self, xrefs):
        """
        Sets the xrefs of this Gene.
        Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 

        :param xrefs: The xrefs of this Gene.
        :type: list[str]
        """

        self._xrefs = xrefs

    @property
    def taxon(self):
        """
        Gets the taxon of this Gene.
        Taxon to which the object belongs

        :return: The taxon of this Gene.
        :rtype: Taxon
        """
        return self._taxon

    @taxon.setter
    def taxon(self, taxon):
        """
        Sets the taxon of this Gene.
        Taxon to which the object belongs

        :param taxon: The taxon of this Gene.
        :type: Taxon
        """

        self._taxon = taxon

    @property
    def transcripts(self):
        """
        Gets the transcripts of this Gene.
        All transcripts belonging to this gene

        :return: The transcripts of this Gene.
        :rtype: list[Transcript]
        """
        return self._transcripts

    @transcripts.setter
    def transcripts(self, transcripts):
        """
        Sets the transcripts of this Gene.
        All transcripts belonging to this gene

        :param transcripts: The transcripts of this Gene.
        :type: list[Transcript]
        """

        self._transcripts = transcripts

    @property
    def sequence_features(self):
        """
        Gets the sequence_features of this Gene.
        Sequence feature representing particular instance on a genome

        :return: The sequence_features of this Gene.
        :rtype: list[SequenceFeature]
        """
        return self._sequence_features

    @sequence_features.setter
    def sequence_features(self, sequence_features):
        """
        Sets the sequence_features of this Gene.
        Sequence feature representing particular instance on a genome

        :param sequence_features: The sequence_features of this Gene.
        :type: list[SequenceFeature]
        """

        self._sequence_features = sequence_features

    @property
    def function_associations(self):
        """
        Gets the function_associations of this Gene.
        GO assocations for wild type gene

        :return: The function_associations of this Gene.
        :rtype: list[Association]
        """
        return self._function_associations

    @function_associations.setter
    def function_associations(self, function_associations):
        """
        Sets the function_associations of this Gene.
        GO assocations for wild type gene

        :param function_associations: The function_associations of this Gene.
        :type: list[Association]
        """

        self._function_associations = function_associations

    @property
    def chromosome(self):
        """
        Gets the chromosome of this Gene.
        chromosome on which this gene is located. This may be redundant with information in sequence_feature objects but is included here for convenience

        :return: The chromosome of this Gene.
        :rtype: Chromosome
        """
        return self._chromosome

    @chromosome.setter
    def chromosome(self, chromosome):
        """
        Sets the chromosome of this Gene.
        chromosome on which this gene is located. This may be redundant with information in sequence_feature objects but is included here for convenience

        :param chromosome: The chromosome of this Gene.
        :type: Chromosome
        """

        self._chromosome = chromosome

    @property
    def full_name(self):
        """
        Gets the full_name of this Gene.
        full name, e.g. Synaptosome Associated Protein 29

        :return: The full_name of this Gene.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """
        Sets the full_name of this Gene.
        full name, e.g. Synaptosome Associated Protein 29

        :param full_name: The full_name of this Gene.
        :type: str
        """

        self._full_name = full_name

    @property
    def homology_associations(self):
        """
        Gets the homology_associations of this Gene.
        orthology and paralogy assocations for this gene

        :return: The homology_associations of this Gene.
        :rtype: list[Association]
        """
        return self._homology_associations

    @homology_associations.setter
    def homology_associations(self, homology_associations):
        """
        Sets the homology_associations of this Gene.
        orthology and paralogy assocations for this gene

        :param homology_associations: The homology_associations of this Gene.
        :type: list[Association]
        """

        self._homology_associations = homology_associations

    @property
    def pathway_associations(self):
        """
        Gets the pathway_associations of this Gene.
        Assocations to pathways in which this gene is involved, including LEGO models

        :return: The pathway_associations of this Gene.
        :rtype: list[Association]
        """
        return self._pathway_associations

    @pathway_associations.setter
    def pathway_associations(self, pathway_associations):
        """
        Sets the pathway_associations of this Gene.
        Assocations to pathways in which this gene is involved, including LEGO models

        :param pathway_associations: The pathway_associations of this Gene.
        :type: list[Association]
        """

        self._pathway_associations = pathway_associations

    @property
    def literature_associations(self):
        """
        Gets the literature_associations of this Gene.
        publications for this gene

        :return: The literature_associations of this Gene.
        :rtype: list[Association]
        """
        return self._literature_associations

    @literature_associations.setter
    def literature_associations(self, literature_associations):
        """
        Sets the literature_associations of this Gene.
        publications for this gene

        :param literature_associations: The literature_associations of this Gene.
        :type: list[Association]
        """

        self._literature_associations = literature_associations

    @property
    def interaction_associations(self):
        """
        Gets the interaction_associations of this Gene.
        associations to genes that interact (may be physical or genetic)

        :return: The interaction_associations of this Gene.
        :rtype: list[Association]
        """
        return self._interaction_associations

    @interaction_associations.setter
    def interaction_associations(self, interaction_associations):
        """
        Sets the interaction_associations of this Gene.
        associations to genes that interact (may be physical or genetic)

        :param interaction_associations: The interaction_associations of this Gene.
        :type: list[Association]
        """

        self._interaction_associations = interaction_associations

    @property
    def disease_associations(self):
        """
        Gets the disease_associations of this Gene.
        diseases associated with alterations of gene

        :return: The disease_associations of this Gene.
        :rtype: list[Association]
        """
        return self._disease_associations

    @disease_associations.setter
    def disease_associations(self, disease_associations):
        """
        Sets the disease_associations of this Gene.
        diseases associated with alterations of gene

        :param disease_associations: The disease_associations of this Gene.
        :type: list[Association]
        """

        self._disease_associations = disease_associations

    @property
    def phenotype_associations(self):
        """
        Gets the phenotype_associations of this Gene.
        phenotypes associated with alterations of gene

        :return: The phenotype_associations of this Gene.
        :rtype: list[Association]
        """
        return self._phenotype_associations

    @phenotype_associations.setter
    def phenotype_associations(self, phenotype_associations):
        """
        Sets the phenotype_associations of this Gene.
        phenotypes associated with alterations of gene

        :param phenotype_associations: The phenotype_associations of this Gene.
        :type: list[Association]
        """

        self._phenotype_associations = phenotype_associations

    @property
    def summaries(self):
        """
        Gets the summaries of this Gene.
        Attributed textual summaries

        :return: The summaries of this Gene.
        :rtype: list[SummaryPropertyValue]
        """
        return self._summaries

    @summaries.setter
    def summaries(self, summaries):
        """
        Sets the summaries of this Gene.
        Attributed textual summaries

        :param summaries: The summaries of this Gene.
        :type: list[SummaryPropertyValue]
        """

        self._summaries = summaries

    @property
    def genotype_associations(self):
        """
        Gets the genotype_associations of this Gene.
        associations to genotypes in which this gene is altered

        :return: The genotype_associations of this Gene.
        :rtype: list[Association]
        """
        return self._genotype_associations

    @genotype_associations.setter
    def genotype_associations(self, genotype_associations):
        """
        Sets the genotype_associations of this Gene.
        associations to genotypes in which this gene is altered

        :param genotype_associations: The genotype_associations of this Gene.
        :type: list[Association]
        """

        self._genotype_associations = genotype_associations

    @property
    def families(self):
        """
        Gets the families of this Gene.
        Families, superfamilies etc to which these gene belongs

        :return: The families of this Gene.
        :rtype: list[NamedObject]
        """
        return self._families

    @families.setter
    def families(self, families):
        """
        Sets the families of this Gene.
        Families, superfamilies etc to which these gene belongs

        :param families: The families of this Gene.
        :type: list[NamedObject]
        """

        self._families = families

    @property
    def systematic_name(self):
        """
        Gets the systematic_name of this Gene.
        E.g. SPBC428.08c for clr4 in PomBase

        :return: The systematic_name of this Gene.
        :rtype: str
        """
        return self._systematic_name

    @systematic_name.setter
    def systematic_name(self, systematic_name):
        """
        Sets the systematic_name of this Gene.
        E.g. SPBC428.08c for clr4 in PomBase

        :param systematic_name: The systematic_name of this Gene.
        :type: str
        """

        self._systematic_name = systematic_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Gene):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
