# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Seq(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, types=None, categories=None, replaced_by=None, synonyms=None, label=None, deprecated=None, id=None, description=None, consider=None, xrefs=None, taxon=None, alphabet=None, md5checksum=None, seqlen=None, residues=None):
        """
        Seq - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'types': 'list[str]',
            'categories': 'list[str]',
            'replaced_by': 'list[str]',
            'synonyms': 'list[SynonymPropertyValue]',
            'label': 'str',
            'deprecated': 'bool',
            'id': 'str',
            'description': 'str',
            'consider': 'list[str]',
            'xrefs': 'list[str]',
            'taxon': 'Taxon',
            'alphabet': 'str',
            'md5checksum': 'str',
            'seqlen': 'str',
            'residues': 'str'
        }

        self.attribute_map = {
            'types': 'types',
            'categories': 'categories',
            'replaced_by': 'replaced_by',
            'synonyms': 'synonyms',
            'label': 'label',
            'deprecated': 'deprecated',
            'id': 'id',
            'description': 'description',
            'consider': 'consider',
            'xrefs': 'xrefs',
            'taxon': 'taxon',
            'alphabet': 'alphabet',
            'md5checksum': 'md5checksum',
            'seqlen': 'seqlen',
            'residues': 'residues'
        }

        self._types = types
        self._categories = categories
        self._replaced_by = replaced_by
        self._synonyms = synonyms
        self._label = label
        self._deprecated = deprecated
        self._id = id
        self._description = description
        self._consider = consider
        self._xrefs = xrefs
        self._taxon = taxon
        self._alphabet = alphabet
        self._md5checksum = md5checksum
        self._seqlen = seqlen
        self._residues = residues

    @property
    def types(self):
        """
        Gets the types of this Seq.

        :return: The types of this Seq.
        :rtype: list[str]
        """
        return self._types

    @types.setter
    def types(self, types):
        """
        Sets the types of this Seq.

        :param types: The types of this Seq.
        :type: list[str]
        """

        self._types = types

    @property
    def categories(self):
        """
        Gets the categories of this Seq.

        :return: The categories of this Seq.
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this Seq.

        :param categories: The categories of this Seq.
        :type: list[str]
        """

        self._categories = categories

    @property
    def replaced_by(self):
        """
        Gets the replaced_by of this Seq.

        :return: The replaced_by of this Seq.
        :rtype: list[str]
        """
        return self._replaced_by

    @replaced_by.setter
    def replaced_by(self, replaced_by):
        """
        Sets the replaced_by of this Seq.

        :param replaced_by: The replaced_by of this Seq.
        :type: list[str]
        """

        self._replaced_by = replaced_by

    @property
    def synonyms(self):
        """
        Gets the synonyms of this Seq.
        list of synonyms or alternate labels

        :return: The synonyms of this Seq.
        :rtype: list[SynonymPropertyValue]
        """
        return self._synonyms

    @synonyms.setter
    def synonyms(self, synonyms):
        """
        Sets the synonyms of this Seq.
        list of synonyms or alternate labels

        :param synonyms: The synonyms of this Seq.
        :type: list[SynonymPropertyValue]
        """

        self._synonyms = synonyms

    @property
    def label(self):
        """
        Gets the label of this Seq.
        RDFS Label

        :return: The label of this Seq.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this Seq.
        RDFS Label

        :param label: The label of this Seq.
        :type: str
        """

        self._label = label

    @property
    def deprecated(self):
        """
        Gets the deprecated of this Seq.
        True if the node is deprecated/obsoleted.

        :return: The deprecated of this Seq.
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """
        Sets the deprecated of this Seq.
        True if the node is deprecated/obsoleted.

        :param deprecated: The deprecated of this Seq.
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def id(self):
        """
        Gets the id of this Seq.
        ID or CURIE e.g. MGI:1201606

        :return: The id of this Seq.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Seq.
        ID or CURIE e.g. MGI:1201606

        :param id: The id of this Seq.
        :type: str
        """

        self._id = id

    @property
    def description(self):
        """
        Gets the description of this Seq.
        Descriptive text for the entity. For ontology classes, this will be a definition.

        :return: The description of this Seq.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Seq.
        Descriptive text for the entity. For ontology classes, this will be a definition.

        :param description: The description of this Seq.
        :type: str
        """

        self._description = description

    @property
    def consider(self):
        """
        Gets the consider of this Seq.

        :return: The consider of this Seq.
        :rtype: list[str]
        """
        return self._consider

    @consider.setter
    def consider(self, consider):
        """
        Sets the consider of this Seq.

        :param consider: The consider of this Seq.
        :type: list[str]
        """

        self._consider = consider

    @property
    def xrefs(self):
        """
        Gets the xrefs of this Seq.
        Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 

        :return: The xrefs of this Seq.
        :rtype: list[str]
        """
        return self._xrefs

    @xrefs.setter
    def xrefs(self, xrefs):
        """
        Sets the xrefs of this Seq.
        Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 

        :param xrefs: The xrefs of this Seq.
        :type: list[str]
        """

        self._xrefs = xrefs

    @property
    def taxon(self):
        """
        Gets the taxon of this Seq.
        Taxon to which the object belongs

        :return: The taxon of this Seq.
        :rtype: Taxon
        """
        return self._taxon

    @taxon.setter
    def taxon(self, taxon):
        """
        Sets the taxon of this Seq.
        Taxon to which the object belongs

        :param taxon: The taxon of this Seq.
        :type: Taxon
        """

        self._taxon = taxon

    @property
    def alphabet(self):
        """
        Gets the alphabet of this Seq.
        one of: DNA, RNA or AA

        :return: The alphabet of this Seq.
        :rtype: str
        """
        return self._alphabet

    @alphabet.setter
    def alphabet(self, alphabet):
        """
        Sets the alphabet of this Seq.
        one of: DNA, RNA or AA

        :param alphabet: The alphabet of this Seq.
        :type: str
        """

        self._alphabet = alphabet

    @property
    def md5checksum(self):
        """
        Gets the md5checksum of this Seq.
        checksum

        :return: The md5checksum of this Seq.
        :rtype: str
        """
        return self._md5checksum

    @md5checksum.setter
    def md5checksum(self, md5checksum):
        """
        Sets the md5checksum of this Seq.
        checksum

        :param md5checksum: The md5checksum of this Seq.
        :type: str
        """

        self._md5checksum = md5checksum

    @property
    def seqlen(self):
        """
        Gets the seqlen of this Seq.
        length of sequence

        :return: The seqlen of this Seq.
        :rtype: str
        """
        return self._seqlen

    @seqlen.setter
    def seqlen(self, seqlen):
        """
        Sets the seqlen of this Seq.
        length of sequence

        :param seqlen: The seqlen of this Seq.
        :type: str
        """

        self._seqlen = seqlen

    @property
    def residues(self):
        """
        Gets the residues of this Seq.
        string representing sequence of residues

        :return: The residues of this Seq.
        :rtype: str
        """
        return self._residues

    @residues.setter
    def residues(self, residues):
        """
        Sets the residues of this Seq.
        string representing sequence of residues

        :param residues: The residues of this Seq.
        :type: str
        """

        self._residues = residues

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Seq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
