# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Transcript(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, types=None, categories=None, replaced_by=None, synonyms=None, label=None, deprecated=None, id=None, description=None, consider=None, xrefs=None, taxon=None, exons=None, cds=None, sequence_features=None, genes=None):
        """
        Transcript - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'types': 'list[str]',
            'categories': 'list[str]',
            'replaced_by': 'list[str]',
            'synonyms': 'list[SynonymPropertyValue]',
            'label': 'str',
            'deprecated': 'bool',
            'id': 'str',
            'description': 'str',
            'consider': 'list[str]',
            'xrefs': 'list[str]',
            'taxon': 'Taxon',
            'exons': 'list[Exon]',
            'cds': 'list[CDS]',
            'sequence_features': 'list[SequenceFeature]',
            'genes': 'list[EntityReference]'
        }

        self.attribute_map = {
            'types': 'types',
            'categories': 'categories',
            'replaced_by': 'replaced_by',
            'synonyms': 'synonyms',
            'label': 'label',
            'deprecated': 'deprecated',
            'id': 'id',
            'description': 'description',
            'consider': 'consider',
            'xrefs': 'xrefs',
            'taxon': 'taxon',
            'exons': 'exons',
            'cds': 'cds',
            'sequence_features': 'sequence_features',
            'genes': 'genes'
        }

        self._types = types
        self._categories = categories
        self._replaced_by = replaced_by
        self._synonyms = synonyms
        self._label = label
        self._deprecated = deprecated
        self._id = id
        self._description = description
        self._consider = consider
        self._xrefs = xrefs
        self._taxon = taxon
        self._exons = exons
        self._cds = cds
        self._sequence_features = sequence_features
        self._genes = genes

    @property
    def types(self):
        """
        Gets the types of this Transcript.

        :return: The types of this Transcript.
        :rtype: list[str]
        """
        return self._types

    @types.setter
    def types(self, types):
        """
        Sets the types of this Transcript.

        :param types: The types of this Transcript.
        :type: list[str]
        """

        self._types = types

    @property
    def categories(self):
        """
        Gets the categories of this Transcript.

        :return: The categories of this Transcript.
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this Transcript.

        :param categories: The categories of this Transcript.
        :type: list[str]
        """

        self._categories = categories

    @property
    def replaced_by(self):
        """
        Gets the replaced_by of this Transcript.

        :return: The replaced_by of this Transcript.
        :rtype: list[str]
        """
        return self._replaced_by

    @replaced_by.setter
    def replaced_by(self, replaced_by):
        """
        Sets the replaced_by of this Transcript.

        :param replaced_by: The replaced_by of this Transcript.
        :type: list[str]
        """

        self._replaced_by = replaced_by

    @property
    def synonyms(self):
        """
        Gets the synonyms of this Transcript.
        list of synonyms or alternate labels

        :return: The synonyms of this Transcript.
        :rtype: list[SynonymPropertyValue]
        """
        return self._synonyms

    @synonyms.setter
    def synonyms(self, synonyms):
        """
        Sets the synonyms of this Transcript.
        list of synonyms or alternate labels

        :param synonyms: The synonyms of this Transcript.
        :type: list[SynonymPropertyValue]
        """

        self._synonyms = synonyms

    @property
    def label(self):
        """
        Gets the label of this Transcript.
        RDFS Label

        :return: The label of this Transcript.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this Transcript.
        RDFS Label

        :param label: The label of this Transcript.
        :type: str
        """

        self._label = label

    @property
    def deprecated(self):
        """
        Gets the deprecated of this Transcript.
        True if the node is deprecated/obsoleted.

        :return: The deprecated of this Transcript.
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """
        Sets the deprecated of this Transcript.
        True if the node is deprecated/obsoleted.

        :param deprecated: The deprecated of this Transcript.
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def id(self):
        """
        Gets the id of this Transcript.
        ID or CURIE e.g. MGI:1201606

        :return: The id of this Transcript.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Transcript.
        ID or CURIE e.g. MGI:1201606

        :param id: The id of this Transcript.
        :type: str
        """

        self._id = id

    @property
    def description(self):
        """
        Gets the description of this Transcript.
        Descriptive text for the entity. For ontology classes, this will be a definition.

        :return: The description of this Transcript.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Transcript.
        Descriptive text for the entity. For ontology classes, this will be a definition.

        :param description: The description of this Transcript.
        :type: str
        """

        self._description = description

    @property
    def consider(self):
        """
        Gets the consider of this Transcript.

        :return: The consider of this Transcript.
        :rtype: list[str]
        """
        return self._consider

    @consider.setter
    def consider(self, consider):
        """
        Sets the consider of this Transcript.

        :param consider: The consider of this Transcript.
        :type: list[str]
        """

        self._consider = consider

    @property
    def xrefs(self):
        """
        Gets the xrefs of this Transcript.
        Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 

        :return: The xrefs of this Transcript.
        :rtype: list[str]
        """
        return self._xrefs

    @xrefs.setter
    def xrefs(self, xrefs):
        """
        Sets the xrefs of this Transcript.
        Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 

        :param xrefs: The xrefs of this Transcript.
        :type: list[str]
        """

        self._xrefs = xrefs

    @property
    def taxon(self):
        """
        Gets the taxon of this Transcript.
        Taxon to which the object belongs

        :return: The taxon of this Transcript.
        :rtype: Taxon
        """
        return self._taxon

    @taxon.setter
    def taxon(self, taxon):
        """
        Sets the taxon of this Transcript.
        Taxon to which the object belongs

        :param taxon: The taxon of this Transcript.
        :type: Taxon
        """

        self._taxon = taxon

    @property
    def exons(self):
        """
        Gets the exons of this Transcript.
        All exons used in this transcript

        :return: The exons of this Transcript.
        :rtype: list[Exon]
        """
        return self._exons

    @exons.setter
    def exons(self, exons):
        """
        Sets the exons of this Transcript.
        All exons used in this transcript

        :param exons: The exons of this Transcript.
        :type: list[Exon]
        """

        self._exons = exons

    @property
    def cds(self):
        """
        Gets the cds of this Transcript.
        All cds used in this transcript

        :return: The cds of this Transcript.
        :rtype: list[CDS]
        """
        return self._cds

    @cds.setter
    def cds(self, cds):
        """
        Sets the cds of this Transcript.
        All cds used in this transcript

        :param cds: The cds of this Transcript.
        :type: list[CDS]
        """

        self._cds = cds

    @property
    def sequence_features(self):
        """
        Gets the sequence_features of this Transcript.
        Sequence feature representing this particular instance on a genome

        :return: The sequence_features of this Transcript.
        :rtype: list[SequenceFeature]
        """
        return self._sequence_features

    @sequence_features.setter
    def sequence_features(self, sequence_features):
        """
        Sets the sequence_features of this Transcript.
        Sequence feature representing this particular instance on a genome

        :param sequence_features: The sequence_features of this Transcript.
        :type: list[SequenceFeature]
        """

        self._sequence_features = sequence_features

    @property
    def genes(self):
        """
        Gets the genes of this Transcript.
        References to any gene objects that have this transcript. This may not be populated if this is contained in a gene object

        :return: The genes of this Transcript.
        :rtype: list[EntityReference]
        """
        return self._genes

    @genes.setter
    def genes(self, genes):
        """
        Sets the genes of this Transcript.
        References to any gene objects that have this transcript. This may not be populated if this is contained in a gene object

        :param genes: The genes of this Transcript.
        :type: list[EntityReference]
        """

        self._genes = genes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Transcript):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
